<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Laravel\Scout\Searchable;
use Spatie\Translatable\HasTranslations;

class Line extends Model
{
    use HasFactory, Searchable, HasTranslations;

    public $translatable = ['name', 'description'];

    protected $fillable = [
        'name',
        'logo',
        'image',
        'description',
        'color',
        'slug',
        'category_id',
        'is_active',
        'is_comex',
    ];

    public function toSearchableArray()
    {
        return [
            'name' => $this->name,
        ];
    }

    protected $casts = [
        'is_active' => 'boolean',
        'is_comex' => 'boolean',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            if ($model->slug == null) {
                $model->slug = Str::slug($model->name);
            }
            ($model->logo == null) ? $model->logo = "lines/logo/".$model->name.".webp" : $model->logo = $model->logo;

        });
    }

    public function products()
    {
        return $this->belongsToMany(Product::class, 'product_line');
    }

}
