<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Spatie\Translatable\HasTranslations;

class Partner extends Model
{
    use HasFactory, HasTranslations;

    public $translatable = ['name', 'description'];

    protected $fillable = [
        'name',
        'image',
        'slug',
        'description',
        'is_active',
        'link'
    ];

    protected $casts = [
        'is_active' => 'boolean',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            if ($model->slug == null) {
                $model->slug = Str::slug($model->name);
            }
            ($model->image == null) ? $model->image = "partners/".$model->slug.".webp" : $model->image = $model->image;
        });
    }
}
